# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SmkOptionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SmkOptionDialog(object):
    def setupUi(self, SmkOptionDialog):
        SmkOptionDialog.setObjectName("SmkOptionDialog")
        SmkOptionDialog.resize(680, 509)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        SmkOptionDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/file-option.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SmkOptionDialog.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(SmkOptionDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(SmkOptionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(SmkOptionDialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGui = QtWidgets.QWidget()
        self.tabGui.setObjectName("tabGui")
        self.gridLayout = QtWidgets.QGridLayout(self.tabGui)
        self.gridLayout.setObjectName("gridLayout")
        self.labelStyle = QtWidgets.QLabel(self.tabGui)
        self.labelStyle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelStyle.setObjectName("labelStyle")
        self.gridLayout.addWidget(self.labelStyle, 0, 0, 1, 1)
        self.comboBoxGuiStyle = QtWidgets.QComboBox(self.tabGui)
        self.comboBoxGuiStyle.setObjectName("comboBoxGuiStyle")
        self.gridLayout.addWidget(self.comboBoxGuiStyle, 0, 1, 1, 3)
        self.labelFont = QtWidgets.QLabel(self.tabGui)
        self.labelFont.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelFont.setObjectName("labelFont")
        self.gridLayout.addWidget(self.labelFont, 1, 0, 1, 1)
        self.comboBoxEnglishFont = QtWidgets.QFontComboBox(self.tabGui)
        self.comboBoxEnglishFont.setObjectName("comboBoxEnglishFont")
        self.gridLayout.addWidget(self.comboBoxEnglishFont, 1, 1, 1, 1)
        self.comboBoxChineseFont = QtWidgets.QFontComboBox(self.tabGui)
        self.comboBoxChineseFont.setObjectName("comboBoxChineseFont")
        self.gridLayout.addWidget(self.comboBoxChineseFont, 1, 2, 1, 1)
        self.spinBoxFontSize = QtWidgets.QSpinBox(self.tabGui)
        self.spinBoxFontSize.setObjectName("spinBoxFontSize")
        self.gridLayout.addWidget(self.spinBoxFontSize, 1, 3, 1, 1)
        self.labelColor = QtWidgets.QLabel(self.tabGui)
        self.labelColor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelColor.setObjectName("labelColor")
        self.gridLayout.addWidget(self.labelColor, 2, 0, 1, 1)
        self.listColor = QtWidgets.QListWidget(self.tabGui)
        self.listColor.setObjectName("listColor")
        self.gridLayout.addWidget(self.listColor, 2, 1, 1, 3)
        self.tabWidget.addTab(self.tabGui, "")
        self.tabContext = QtWidgets.QWidget()
        self.tabContext.setObjectName("tabContext")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabContext)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.labelCSS = QtWidgets.QLabel(self.tabContext)
        self.labelCSS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCSS.setObjectName("labelCSS")
        self.gridLayout_7.addWidget(self.labelCSS, 0, 0, 1, 1)
        self.lineEditCSSURL = QtWidgets.QLineEdit(self.tabContext)
        self.lineEditCSSURL.setObjectName("lineEditCSSURL")
        self.gridLayout_7.addWidget(self.lineEditCSSURL, 0, 1, 1, 1)
        self.buttonCSSURL = QtWidgets.QPushButton(self.tabContext)
        self.buttonCSSURL.setMaximumSize(QtCore.QSize(32, 32))
        self.buttonCSSURL.setObjectName("buttonCSSURL")
        self.gridLayout_7.addWidget(self.buttonCSSURL, 0, 2, 1, 1)
        self.labelMathJax = QtWidgets.QLabel(self.tabContext)
        self.labelMathJax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMathJax.setObjectName("labelMathJax")
        self.gridLayout_7.addWidget(self.labelMathJax, 1, 0, 1, 1)
        self.lineEditMathJaxURL = QtWidgets.QLineEdit(self.tabContext)
        self.lineEditMathJaxURL.setObjectName("lineEditMathJaxURL")
        self.gridLayout_7.addWidget(self.lineEditMathJaxURL, 1, 1, 1, 1)
        self.buttonMathJaxURL = QtWidgets.QPushButton(self.tabContext)
        self.buttonMathJaxURL.setMaximumSize(QtCore.QSize(32, 32))
        self.buttonMathJaxURL.setObjectName("buttonMathJaxURL")
        self.gridLayout_7.addWidget(self.buttonMathJaxURL, 1, 2, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tabContext)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabHeader = QtWidgets.QWidget()
        self.tabHeader.setObjectName("tabHeader")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabHeader)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelHeader = QtWidgets.QLabel(self.tabHeader)
        self.labelHeader.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelHeader.setObjectName("labelHeader")
        self.gridLayout_2.addWidget(self.labelHeader, 0, 0, 1, 1)
        self.textEditHeader = QtWidgets.QPlainTextEdit(self.tabHeader)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.textEditHeader.setFont(font)
        self.textEditHeader.setObjectName("textEditHeader")
        self.gridLayout_2.addWidget(self.textEditHeader, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tabHeader, "")
        self.tabHat = QtWidgets.QWidget()
        self.tabHat.setObjectName("tabHat")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabHat)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelHat = QtWidgets.QLabel(self.tabHat)
        self.labelHat.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelHat.setObjectName("labelHat")
        self.gridLayout_4.addWidget(self.labelHat, 0, 0, 1, 1)
        self.textEditHat = QtWidgets.QPlainTextEdit(self.tabHat)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.textEditHat.setFont(font)
        self.textEditHat.setObjectName("textEditHat")
        self.gridLayout_4.addWidget(self.textEditHat, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tabHat, "")
        self.tabTail = QtWidgets.QWidget()
        self.tabTail.setObjectName("tabTail")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabTail)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.labelTail = QtWidgets.QLabel(self.tabTail)
        self.labelTail.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelTail.setObjectName("labelTail")
        self.gridLayout_5.addWidget(self.labelTail, 0, 0, 1, 1)
        self.textEditTail = QtWidgets.QPlainTextEdit(self.tabTail)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.textEditTail.setFont(font)
        self.textEditTail.setObjectName("textEditTail")
        self.gridLayout_5.addWidget(self.textEditTail, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tabTail, "")
        self.tabFoot = QtWidgets.QWidget()
        self.tabFoot.setObjectName("tabFoot")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabFoot)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelFoot = QtWidgets.QLabel(self.tabFoot)
        self.labelFoot.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelFoot.setObjectName("labelFoot")
        self.gridLayout_6.addWidget(self.labelFoot, 0, 0, 1, 1)
        self.textEditFoot = QtWidgets.QPlainTextEdit(self.tabFoot)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.textEditFoot.setFont(font)
        self.textEditFoot.setObjectName("textEditFoot")
        self.gridLayout_6.addWidget(self.textEditFoot, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tabFoot, "")
        self.gridLayout_7.addWidget(self.tabWidget_2, 2, 0, 1, 3)
        self.tabWidget.addTab(self.tabContext, "")
        self.tabOptions = QtWidgets.QWidget()
        self.tabOptions.setObjectName("tabOptions")
        self.comboBoxSyncScroll = QtWidgets.QComboBox(self.tabOptions)
        self.comboBoxSyncScroll.setGeometry(QtCore.QRect(210, 200, 201, 31))
        self.comboBoxSyncScroll.setObjectName("comboBoxSyncScroll")
        self.comboBoxSyncScroll.addItem("")
        self.comboBoxSyncScroll.addItem("")
        self.label = QtWidgets.QLabel(self.tabOptions)
        self.label.setGeometry(QtCore.QRect(40, 200, 161, 21))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tabOptions, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(SmkOptionDialog)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(3)
        self.buttonBox.accepted.connect(SmkOptionDialog.accept)
        self.buttonBox.rejected.connect(SmkOptionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SmkOptionDialog)

    def retranslateUi(self, SmkOptionDialog):
        _translate = QtCore.QCoreApplication.translate
        SmkOptionDialog.setWindowTitle(_translate("SmkOptionDialog", "Smark Option"))
        self.labelStyle.setText(_translate("SmkOptionDialog", "Qt Gui Style:"))
        self.labelFont.setText(_translate("SmkOptionDialog", "Editor Font:"))
        self.labelColor.setText(_translate("SmkOptionDialog", "Syntax Color:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGui), _translate("SmkOptionDialog", "Gui"))
        self.labelCSS.setText(_translate("SmkOptionDialog", "CSS URL:"))
        self.buttonCSSURL.setText(_translate("SmkOptionDialog", "..."))
        self.labelMathJax.setText(_translate("SmkOptionDialog", "MathJax URL:"))
        self.buttonMathJaxURL.setText(_translate("SmkOptionDialog", "..."))
        self.labelHeader.setText(_translate("SmkOptionDialog", "Insert Context between <header> and </header> :"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabHeader), _translate("SmkOptionDialog", "HTML Header"))
        self.labelHat.setText(_translate("SmkOptionDialog", "<html><head/><body><p>Insert Context after &lt;body&gt; :</p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabHat), _translate("SmkOptionDialog", "HTML Hat"))
        self.labelTail.setText(_translate("SmkOptionDialog", "Insert Context before </body>:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabTail), _translate("SmkOptionDialog", "HTML Tail"))
        self.labelFoot.setText(_translate("SmkOptionDialog", "Insert Context after </body> :"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabFoot), _translate("SmkOptionDialog", "HTML Foot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabContext), _translate("SmkOptionDialog", "Context"))
        self.comboBoxSyncScroll.setCurrentText(_translate("SmkOptionDialog", "MD2Html"))
        self.comboBoxSyncScroll.setItemText(0, _translate("SmkOptionDialog", "MD2Html"))
        self.comboBoxSyncScroll.setItemText(1, _translate("SmkOptionDialog", "Html2MD"))
        self.label.setText(_translate("SmkOptionDialog", "Sync Scrolling Method:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOptions), _translate("SmkOptionDialog", "Options"))

import icon_rc
