# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SmkMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SmkMainWindow(object):
    def setupUi(self, SmkMainWindow):
        SmkMainWindow.setObjectName("SmkMainWindow")
        SmkMainWindow.resize(1113, 686)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        SmkMainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/LOGO.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SmkMainWindow.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(SmkMainWindow)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.htmlView = SmkHtmlWidget(self.splitter)
        self.htmlView.setObjectName("htmlView")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.markView = SmkMarkWidget(self.layoutWidget)
        self.markView.setObjectName("markView")
        self.verticalLayout.addWidget(self.markView)
        self.widgetFind = QtWidgets.QWidget(self.layoutWidget)
        self.widgetFind.setObjectName("widgetFind")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widgetFind)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditFind = QtWidgets.QLineEdit(self.widgetFind)
        self.lineEditFind.setObjectName("lineEditFind")
        self.horizontalLayout.addWidget(self.lineEditFind)
        self.buttonFindPrev = QtWidgets.QPushButton(self.widgetFind)
        self.buttonFindPrev.setObjectName("buttonFindPrev")
        self.horizontalLayout.addWidget(self.buttonFindPrev)
        self.buttonFindNext = QtWidgets.QPushButton(self.widgetFind)
        self.buttonFindNext.setObjectName("buttonFindNext")
        self.horizontalLayout.addWidget(self.buttonFindNext)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.checkBoxCase = QtWidgets.QCheckBox(self.widgetFind)
        self.checkBoxCase.setChecked(True)
        self.checkBoxCase.setObjectName("checkBoxCase")
        self.gridLayout_3.addWidget(self.checkBoxCase, 1, 0, 1, 1)
        self.checkBoxWholeWord = QtWidgets.QCheckBox(self.widgetFind)
        self.checkBoxWholeWord.setChecked(True)
        self.checkBoxWholeWord.setObjectName("checkBoxWholeWord")
        self.gridLayout_3.addWidget(self.checkBoxWholeWord, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(147, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditReplace = QtWidgets.QLineEdit(self.widgetFind)
        self.lineEditReplace.setObjectName("lineEditReplace")
        self.horizontalLayout_2.addWidget(self.lineEditReplace)
        self.buttonReplace = QtWidgets.QPushButton(self.widgetFind)
        self.buttonReplace.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonReplace.setObjectName("buttonReplace")
        self.horizontalLayout_2.addWidget(self.buttonReplace)
        self.buttonReplaceAll = QtWidgets.QPushButton(self.widgetFind)
        self.buttonReplaceAll.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonReplaceAll.setObjectName("buttonReplaceAll")
        self.horizontalLayout_2.addWidget(self.buttonReplaceAll)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 3)
        self.checkBoxCase.raise_()
        self.checkBoxWholeWord.raise_()
        self.verticalLayout.addWidget(self.widgetFind)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        SmkMainWindow.setCentralWidget(self.widget)
        self.menubar = QtWidgets.QMenuBar(SmkMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 19))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFormat = QtWidgets.QMenu(self.menubar)
        self.menuFormat.setObjectName("menuFormat")
        self.menuInsert = QtWidgets.QMenu(self.menubar)
        self.menuInsert.setObjectName("menuInsert")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        SmkMainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(SmkMainWindow)
        self.toolBar.setIconSize(QtCore.QSize(16, 16))
        self.toolBar.setObjectName("toolBar")
        SmkMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtWidgets.QAction(SmkMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/file-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(SmkMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/file-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(SmkMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/file-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(SmkMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/file-saveas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon4)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionClose = QtWidgets.QAction(SmkMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/file-close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon5)
        self.actionClose.setObjectName("actionClose")
        self.actionPrint = QtWidgets.QAction(SmkMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon6)
        self.actionPrint.setObjectName("actionPrint")
        self.actionQuite = QtWidgets.QAction(SmkMainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/file-quite.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuite.setIcon(icon7)
        self.actionQuite.setObjectName("actionQuite")
        self.actionPreview = QtWidgets.QAction(SmkMainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/view-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreview.setIcon(icon8)
        self.actionPreview.setObjectName("actionPreview")
        self.actionReadOnly = QtWidgets.QAction(SmkMainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/view-read-only.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReadOnly.setIcon(icon9)
        self.actionReadOnly.setObjectName("actionReadOnly")
        self.actionEditOnly = QtWidgets.QAction(SmkMainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/view-edit-only.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditOnly.setIcon(icon10)
        self.actionEditOnly.setObjectName("actionEditOnly")
        self.actionFullScreen = QtWidgets.QAction(SmkMainWindow)
        self.actionFullScreen.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/view-fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFullScreen.setIcon(icon11)
        self.actionFullScreen.setObjectName("actionFullScreen")
        self.actionFlush = QtWidgets.QAction(SmkMainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/edit-flush.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFlush.setIcon(icon12)
        self.actionFlush.setObjectName("actionFlush")
        self.actionCut = QtWidgets.QAction(SmkMainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon/edit-cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon13)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(SmkMainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icon/edit-copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon14)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(SmkMainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icon/edit-paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon15)
        self.actionPaste.setObjectName("actionPaste")
        self.actionRedo = QtWidgets.QAction(SmkMainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icon/edit-undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon16)
        self.actionRedo.setObjectName("actionRedo")
        self.actionUndo = QtWidgets.QAction(SmkMainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icon/edit-redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon17)
        self.actionUndo.setObjectName("actionUndo")
        self.actionFind = QtWidgets.QAction(SmkMainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icon/edit-find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFind.setIcon(icon18)
        self.actionFind.setObjectName("actionFind")
        self.actionViewHTML = QtWidgets.QAction(SmkMainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icon/edit-view-html.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewHTML.setIcon(icon19)
        self.actionViewHTML.setObjectName("actionViewHTML")
        self.actionFormatBlod = QtWidgets.QAction(SmkMainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icon/format-blod.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatBlod.setIcon(icon20)
        self.actionFormatBlod.setObjectName("actionFormatBlod")
        self.actionFormatItalic = QtWidgets.QAction(SmkMainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icon/format-italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatItalic.setIcon(icon21)
        self.actionFormatItalic.setObjectName("actionFormatItalic")
        self.actionFormatUnderline = QtWidgets.QAction(SmkMainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icon/format-underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatUnderline.setIcon(icon22)
        self.actionFormatUnderline.setObjectName("actionFormatUnderline")
        self.actionFormatBigger = QtWidgets.QAction(SmkMainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icon/format-bigger.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatBigger.setIcon(icon23)
        self.actionFormatBigger.setObjectName("actionFormatBigger")
        self.actionFormatSmaller = QtWidgets.QAction(SmkMainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/icon/format-smaller.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatSmaller.setIcon(icon24)
        self.actionFormatSmaller.setObjectName("actionFormatSmaller")
        self.actionFormatSub = QtWidgets.QAction(SmkMainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/icon/format-sub.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatSub.setIcon(icon25)
        self.actionFormatSub.setObjectName("actionFormatSub")
        self.actionFormatSup = QtWidgets.QAction(SmkMainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/icon/format-sup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatSup.setIcon(icon26)
        self.actionFormatSup.setObjectName("actionFormatSup")
        self.actionFormatCode = QtWidgets.QAction(SmkMainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/icon/format-code.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatCode.setIcon(icon27)
        self.actionFormatCode.setObjectName("actionFormatCode")
        self.actionFormatQuote = QtWidgets.QAction(SmkMainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/icon/format-quote.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatQuote.setIcon(icon28)
        self.actionFormatQuote.setObjectName("actionFormatQuote")
        self.actionAlignLeft = QtWidgets.QAction(SmkMainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/icon/align-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAlignLeft.setIcon(icon29)
        self.actionAlignLeft.setObjectName("actionAlignLeft")
        self.actionAlignRight = QtWidgets.QAction(SmkMainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/icon/align-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAlignRight.setIcon(icon30)
        self.actionAlignRight.setObjectName("actionAlignRight")
        self.actionAlignCenter = QtWidgets.QAction(SmkMainWindow)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/icon/align-center.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAlignCenter.setIcon(icon31)
        self.actionAlignCenter.setObjectName("actionAlignCenter")
        self.actionInsertImage = QtWidgets.QAction(SmkMainWindow)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/icon/insert-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertImage.setIcon(icon32)
        self.actionInsertImage.setObjectName("actionInsertImage")
        self.actionInsertLink = QtWidgets.QAction(SmkMainWindow)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/icon/insert-link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertLink.setIcon(icon33)
        self.actionInsertLink.setObjectName("actionInsertLink")
        self.actionInsertMathJax = QtWidgets.QAction(SmkMainWindow)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/icon/insert-formation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertMathJax.setIcon(icon34)
        self.actionInsertMathJax.setObjectName("actionInsertMathJax")
        self.actionAboutQt = QtWidgets.QAction(SmkMainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionAboutSmark = QtWidgets.QAction(SmkMainWindow)
        self.actionAboutSmark.setObjectName("actionAboutSmark")
        self.actionOption = QtWidgets.QAction(SmkMainWindow)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/icon/file-option.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOption.setIcon(icon35)
        self.actionOption.setObjectName("actionOption")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionOption)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuite)
        self.menuView.addAction(self.actionReadOnly)
        self.menuView.addAction(self.actionPreview)
        self.menuView.addAction(self.actionEditOnly)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFullScreen)
        self.menuEdit.addAction(self.actionFlush)
        self.menuEdit.addAction(self.actionViewHTML)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFind)
        self.menuFormat.addAction(self.actionFormatBlod)
        self.menuFormat.addAction(self.actionFormatItalic)
        self.menuFormat.addAction(self.actionFormatUnderline)
        self.menuFormat.addSeparator()
        self.menuFormat.addAction(self.actionFormatBigger)
        self.menuFormat.addAction(self.actionFormatSmaller)
        self.menuFormat.addSeparator()
        self.menuFormat.addAction(self.actionFormatSub)
        self.menuFormat.addAction(self.actionFormatSup)
        self.menuFormat.addSeparator()
        self.menuFormat.addAction(self.actionFormatCode)
        self.menuFormat.addAction(self.actionFormatQuote)
        self.menuFormat.addSeparator()
        self.menuFormat.addAction(self.actionAlignLeft)
        self.menuFormat.addAction(self.actionAlignRight)
        self.menuFormat.addAction(self.actionAlignCenter)
        self.menuInsert.addAction(self.actionInsertImage)
        self.menuInsert.addAction(self.actionInsertLink)
        self.menuInsert.addAction(self.actionInsertMathJax)
        self.menuHelp.addAction(self.actionAboutQt)
        self.menuHelp.addAction(self.actionAboutSmark)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuInsert.menuAction())
        self.menubar.addAction(self.menuFormat.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSaveAs)
        self.toolBar.addAction(self.actionClose)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addAction(self.actionOption)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPreview)
        self.toolBar.addAction(self.actionReadOnly)
        self.toolBar.addAction(self.actionEditOnly)
        self.toolBar.addAction(self.actionFullScreen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFlush)
        self.toolBar.addAction(self.actionViewHTML)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionFind)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionInsertImage)
        self.toolBar.addAction(self.actionInsertLink)
        self.toolBar.addAction(self.actionInsertMathJax)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFormatBlod)
        self.toolBar.addAction(self.actionFormatItalic)
        self.toolBar.addAction(self.actionFormatUnderline)
        self.toolBar.addAction(self.actionFormatCode)
        self.toolBar.addAction(self.actionFormatQuote)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFormatBigger)
        self.toolBar.addAction(self.actionFormatSmaller)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFormatSub)
        self.toolBar.addAction(self.actionFormatSup)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAlignRight)
        self.toolBar.addAction(self.actionAlignCenter)
        self.toolBar.addAction(self.actionAlignLeft)
        self.toolBar.addSeparator()

        self.retranslateUi(SmkMainWindow)
        QtCore.QMetaObject.connectSlotsByName(SmkMainWindow)

    def retranslateUi(self, SmkMainWindow):
        _translate = QtCore.QCoreApplication.translate
        SmkMainWindow.setWindowTitle(_translate("SmkMainWindow", "Smark"))
        self.buttonFindPrev.setText(_translate("SmkMainWindow", "Preview"))
        self.buttonFindNext.setText(_translate("SmkMainWindow", "Next"))
        self.checkBoxCase.setText(_translate("SmkMainWindow", "Case-sensitive"))
        self.checkBoxWholeWord.setText(_translate("SmkMainWindow", "Whole word match"))
        self.buttonReplace.setText(_translate("SmkMainWindow", "Replace"))
        self.buttonReplaceAll.setText(_translate("SmkMainWindow", "Replace All"))
        self.menuFile.setTitle(_translate("SmkMainWindow", "File (&F)"))
        self.menuView.setTitle(_translate("SmkMainWindow", "View (&V)"))
        self.menuEdit.setTitle(_translate("SmkMainWindow", "Edit (&E)"))
        self.menuFormat.setTitle(_translate("SmkMainWindow", "Format (&F)"))
        self.menuInsert.setTitle(_translate("SmkMainWindow", "Insert (&I)"))
        self.menuHelp.setTitle(_translate("SmkMainWindow", "Help (&H)"))
        self.toolBar.setWindowTitle(_translate("SmkMainWindow", "Tool Bar"))
        self.actionNew.setText(_translate("SmkMainWindow", "New"))
        self.actionNew.setShortcut(_translate("SmkMainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("SmkMainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("SmkMainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("SmkMainWindow", "Save"))
        self.actionSave.setShortcut(_translate("SmkMainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("SmkMainWindow", "Save As"))
        self.actionSaveAs.setShortcut(_translate("SmkMainWindow", "Ctrl+Shift+S"))
        self.actionClose.setText(_translate("SmkMainWindow", "Close"))
        self.actionClose.setShortcut(_translate("SmkMainWindow", "Ctrl+W"))
        self.actionPrint.setText(_translate("SmkMainWindow", "Print"))
        self.actionPrint.setShortcut(_translate("SmkMainWindow", "Ctrl+P"))
        self.actionQuite.setText(_translate("SmkMainWindow", "Quite"))
        self.actionQuite.setShortcut(_translate("SmkMainWindow", "Ctrl+Q"))
        self.actionPreview.setText(_translate("SmkMainWindow", "Preview"))
        self.actionPreview.setShortcut(_translate("SmkMainWindow", "F6"))
        self.actionReadOnly.setText(_translate("SmkMainWindow", "Read Only"))
        self.actionReadOnly.setShortcut(_translate("SmkMainWindow", "F7"))
        self.actionEditOnly.setText(_translate("SmkMainWindow", "Edit Only"))
        self.actionEditOnly.setShortcut(_translate("SmkMainWindow", "F8"))
        self.actionFullScreen.setText(_translate("SmkMainWindow", "Full Screen"))
        self.actionFullScreen.setShortcut(_translate("SmkMainWindow", "F11"))
        self.actionFlush.setText(_translate("SmkMainWindow", "Flush"))
        self.actionFlush.setShortcut(_translate("SmkMainWindow", "F5"))
        self.actionCut.setText(_translate("SmkMainWindow", "Cut"))
        self.actionCut.setShortcut(_translate("SmkMainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("SmkMainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("SmkMainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("SmkMainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("SmkMainWindow", "Ctrl+P"))
        self.actionRedo.setText(_translate("SmkMainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("SmkMainWindow", "Ctrl+Y"))
        self.actionUndo.setText(_translate("SmkMainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("SmkMainWindow", "Ctrl+Z"))
        self.actionFind.setText(_translate("SmkMainWindow", "Find"))
        self.actionFind.setShortcut(_translate("SmkMainWindow", "Ctrl+F"))
        self.actionViewHTML.setText(_translate("SmkMainWindow", "View HTML Source"))
        self.actionViewHTML.setShortcut(_translate("SmkMainWindow", "Ctrl+Shift+C"))
        self.actionFormatBlod.setText(_translate("SmkMainWindow", "Blod"))
        self.actionFormatBlod.setShortcut(_translate("SmkMainWindow", "Ctrl+B"))
        self.actionFormatItalic.setText(_translate("SmkMainWindow", "Italic"))
        self.actionFormatItalic.setShortcut(_translate("SmkMainWindow", "Ctrl+I"))
        self.actionFormatUnderline.setText(_translate("SmkMainWindow", "Under Line "))
        self.actionFormatUnderline.setShortcut(_translate("SmkMainWindow", "Ctrl+U"))
        self.actionFormatBigger.setText(_translate("SmkMainWindow", "Bigger"))
        self.actionFormatBigger.setShortcut(_translate("SmkMainWindow", "Ctrl+]"))
        self.actionFormatSmaller.setText(_translate("SmkMainWindow", "Smaller"))
        self.actionFormatSmaller.setShortcut(_translate("SmkMainWindow", "Ctrl+["))
        self.actionFormatSub.setText(_translate("SmkMainWindow", "Sub"))
        self.actionFormatSub.setShortcut(_translate("SmkMainWindow", "Ctrl+Down"))
        self.actionFormatSup.setText(_translate("SmkMainWindow", "Sup"))
        self.actionFormatSup.setShortcut(_translate("SmkMainWindow", "Ctrl+Up"))
        self.actionFormatCode.setText(_translate("SmkMainWindow", "Code"))
        self.actionFormatCode.setShortcut(_translate("SmkMainWindow", "Ctrl+`"))
        self.actionFormatQuote.setText(_translate("SmkMainWindow", "Quote"))
        self.actionFormatQuote.setShortcut(_translate("SmkMainWindow", "Ctrl+\'"))
        self.actionAlignLeft.setText(_translate("SmkMainWindow", "Align Left"))
        self.actionAlignLeft.setShortcut(_translate("SmkMainWindow", "Ctrl+L"))
        self.actionAlignRight.setText(_translate("SmkMainWindow", "Align Right"))
        self.actionAlignRight.setShortcut(_translate("SmkMainWindow", "Ctrl+R"))
        self.actionAlignCenter.setText(_translate("SmkMainWindow", "Align Center"))
        self.actionAlignCenter.setShortcut(_translate("SmkMainWindow", "Ctrl+E"))
        self.actionInsertImage.setText(_translate("SmkMainWindow", "Image"))
        self.actionInsertImage.setShortcut(_translate("SmkMainWindow", "Ctrl+Shift+I, Ctrl+Shift+P"))
        self.actionInsertLink.setText(_translate("SmkMainWindow", "Link"))
        self.actionInsertLink.setShortcut(_translate("SmkMainWindow", "Ctrl+Shift+L"))
        self.actionInsertMathJax.setText(_translate("SmkMainWindow", "MathJax"))
        self.actionInsertMathJax.setToolTip(_translate("SmkMainWindow", "MathJax"))
        self.actionInsertMathJax.setShortcut(_translate("SmkMainWindow", "Ctrl+Shift+M"))
        self.actionAboutQt.setText(_translate("SmkMainWindow", "About Qt"))
        self.actionAboutSmark.setText(_translate("SmkMainWindow", "About Smark"))
        self.actionOption.setText(_translate("SmkMainWindow", "Option"))

#from Smark.SmkHtmlWidget import SmkHtmlWidget
#from Smark.SmkMarkWidget import SmkMarkWidget
#import icon_rc
